package org.main.engine.events;

public enum EngineEventType {
	SUBMITTED_TASK_FOR_EXECUTION,
	TASK_SPILLED_TO_DISK,
	TASK_RECOVERED_FROM_DISK,
	STARTED_TASK_PROCESSING,
	TASK_COMPLETED,
	TASK_FAILED_TO_EXECUTE
}
